CELL 1: IMPORTS

In [2]:
import pandas as pd
import pickle
import os

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

CELL 2: LOAD DATA

In [4]:
import os
print(os.getcwd())

c:\Users\RUCHI\Urban Safety Intelligence System\notebooks

In [17]:
import os

print(os.listdir("../data"))

['crime_data.csv', 'fir_text_data.csv']

In [16]:
import pandas as pd

df = pd.read_csv("../data/fir_text_data.csv")
print(df.head())

                           text crime_type
0  Mobile stolen from bus stand      Theft
1      Bike stolen near college      Theft
2      Chain snatching incident      Theft
3    Person attacked with knife    Assault
4         Group fight near road    Assault

In [8]:
# Check current working directory
print("Current Path:", os.getcwd())

# Define possible paths
paths = [
    "../data/fir_text_data.csv",
    "data/fir_text_data.csv",
    "fir_text_data.csv"
]

file_path = None

# Find correct path
for path in paths:
    if os.path.exists(path):
        file_path = path
        break

if file_path is None:
    raise FileNotFoundError("❌ fir_text_data.csv not found. Check your folder!")

print("✅ Found file at:", file_path)

# Load data
df = pd.read_csv(file_path)

df.head()

Current Path: c:\Users\RUCHI\Urban Safety Intelligence System\notebooks
✅ Found file at: ../data/fir_text_data.csv

                           text crime_type
0  Mobile stolen from bus stand      Theft
1      Bike stolen near college      Theft
2      Chain snatching incident      Theft
3    Person attacked with knife    Assault
4         Group fight near road    Assault

CELL 3: CHECK DATA

In [9]:
print("Shape:", df.shape)
print("\nColumns:", df.columns)
print("\nNull values:\n", df.isnull().sum())

Shape: (12, 2)

Columns: Index(['text', 'crime_type'], dtype='object')

Null values:
 text          0
crime_type    0
dtype: int64

CELL 4: CLEAN DATA

In [10]:
df = df.dropna()

df['text'] = df['text'].astype(str)
df['crime_type'] = df['crime_type'].astype(str)

df.head()

                           text crime_type
0  Mobile stolen from bus stand      Theft
1      Bike stolen near college      Theft
2      Chain snatching incident      Theft
3    Person attacked with knife    Assault
4         Group fight near road    Assault

CELL 5: SPLIT DATA

In [11]:
X = df['text']
y = df['crime_type']

CELL 6: VECTORIZATION

In [12]:
vectorizer = TfidfVectorizer()

X_vec = vectorizer.fit_transform(X)

print("Vectorized shape:", X_vec.shape)

Vectorized shape: (12, 41)

CELL 7: TRAIN MODEL

In [13]:
model = LogisticRegression()

model.fit(X_vec, y)

print("✅ Model trained successfully")

✅ Model trained successfully

CELL 8: TEST MODEL

In [14]:
sample = ["Mobile stolen near bus stand"]

sample_vec = vectorizer.transform(sample)

prediction = model.predict(sample_vec)

print("Prediction:", prediction[0])

Prediction: Theft

CELL 9: SAVE MODEL

In [15]:
# Create folder if not exists
save_path = "../backend/models"
os.makedirs(save_path, exist_ok=True)

# Save model + vectorizer
pickle.dump((model, vectorizer), open(f"{save_path}/classifier.pkl", "wb"))

print("✅ Model saved successfully at:", save_path)

✅ Model saved successfully at: ../backend/models

In [18]:
df = pd.read_csv("../data/fir_text_data.csv")
print(df.shape)

(12, 2)

CELL: HOTSPOT MODEL TRAINING